<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class RecurringBillingRule extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'client_id',
        'created_by',
        'status',
        'frequency',
        'start_date',
        'end_date',
        'last_generated_at',
        'next_generation_date',
        'currency_id',
        'base_currency',
        'exchange_rate',
        'subtotal',
        'discount_amount',
        'tax_amount',
        'total_amount',
        'coupon_id',
        'coupon_discount',
        'terms_conditions',
        'client_notes',
        'internal_notes',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'client_id' => 'integer',
            'created_by' => 'integer',
            'currency_id' => 'integer',
            'base_currency' => 'string',
            'coupon_id' => 'integer',
            'exchange_rate' => 'decimal:4',
            'subtotal' => 'decimal:2',
            'discount_amount' => 'decimal:2',
            'tax_amount' => 'decimal:2',
            'total_amount' => 'decimal:2',
            'coupon_discount' => 'decimal:2',
            'start_date' => 'date',
            'end_date' => 'date',
            'last_generated_at' => 'datetime',
            'next_generation_date' => 'date',
        ];
    }

    /**
     * Get the items belonging to this rule.
     *
     * @return HasMany<RecurringBillingRuleItem, $this>
     */
    public function items(): HasMany
    {
        return $this->hasMany(RecurringBillingRuleItem::class, 'recurring_billing_rule_id');
    }

    /**
     * Get the invoices generated by this rule.
     *
     * @return HasMany<Invoice, $this>
     */
    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class, 'recurring_rule_id');
    }

    /**
     * Get the client that this rule belongs to.
     *
     * @return BelongsTo<User, $this>
     */
    public function client(): BelongsTo
    {
        return $this->belongsTo(User::class, 'client_id');
    }

    /**
     * Get the user who created this rule.
     *
     * @return BelongsTo<User, $this>
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Get the currency.
     *
     * @return BelongsTo<Currency, $this>
     */
    public function currency(): BelongsTo
    {
        return $this->belongsTo(Currency::class, 'currency_id');
    }

    /**
     * Get the coupon.
     *
     * @return BelongsTo<DiscountCoupon, $this>
     */
    public function coupon(): BelongsTo
    {
        return $this->belongsTo(DiscountCoupon::class, 'coupon_id');
    }

    /**
     * Recalculate totals for the rule based on its items and coupon.
     */
    public function recalculateTotals(): void
    {
        $subtotal = 0.00;
        $itemsDiscount = 0.00;
        $itemsTax = 0.00;

        foreach ($this->items as $item) {
            $qty = (float) $item->quantity;
            $price = (float) $item->unit_price;
            $discPercent = (float) $item->discount_percent;
            $taxRate = $item->tax_type === 'none' ? 0.00 : (float) $item->tax_rate;

            $itemSubtotal = $qty * $price;
            $itemDiscount = $itemSubtotal * ($discPercent / 100);
            $itemTaxable = $itemSubtotal - $itemDiscount;
            $itemTax = $itemTaxable * ($taxRate / 100);
            $itemTotal = $itemTaxable + $itemTax;

            if (abs((float)$item->discount_amount - $itemDiscount) > 0.0001 ||
                abs((float)$item->tax_amount - $itemTax) > 0.0001 ||
                abs((float)$item->total_amount - $itemTotal) > 0.0001 ||
                abs((float)$item->tax_rate - $taxRate) > 0.0001) {
                $item->update([
                    'discount_amount' => $itemDiscount,
                    'tax_rate' => $taxRate,
                    'tax_amount' => $itemTax,
                    'total_amount' => $itemTotal,
                ]);
            }

            $subtotal += $itemSubtotal;
            $itemsDiscount += $itemDiscount;
            $itemsTax += $itemTax;
        }

        $couponDiscount = 0.00;
        if ($this->coupon && $this->coupon->isValidForAmount($subtotal - $itemsDiscount)) {
            if ($this->coupon->type === 'percentage') {
                $couponDiscount = ($subtotal - $itemsDiscount) * ((float) $this->coupon->value / 100);
                if ($this->coupon->maximum_discount !== null && $couponDiscount > (float) $this->coupon->maximum_discount) {
                    $couponDiscount = (float) $this->coupon->maximum_discount;
                }
            } else {
                $couponDiscount = (float) $this->coupon->value;
                if ($couponDiscount > ($subtotal - $itemsDiscount)) {
                    $couponDiscount = $subtotal - $itemsDiscount;
                }
            }
        }

        $discountAmount = $itemsDiscount + $couponDiscount;
        $taxAmount = $itemsTax;
        $totalAmount = $subtotal - $discountAmount + $taxAmount;

        $this->forceFill([
            'subtotal' => $subtotal,
            'discount_amount' => $discountAmount,
            'tax_amount' => $taxAmount,
            'total_amount' => $totalAmount,
            'coupon_discount' => $couponDiscount,
        ])->saveQuietly();
    }
}
